In [3]:
# how can we check shape and size of an array?
import numpy as np
a=np.array([1,34,89,9900])


In [4]:
a

array([   1,   34,   89, 9900])

In [5]:
print("total shape=",a.shape)
print("total elements=",a.size)

total shape= (4,)
total elements= 4


In [6]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("total shape=",b.shape)
print("total elements=",b.size)

total shape= (3, 3)
total elements= 9


In [12]:
# images===> pixels(0-255) ==> 0pzx black , 255 white ==> normalize(0-1)px
# initially weights==>0,1
# optimization == 0,1
# matrix ==> n(rows) , n(columns)
# symmetric ==> n(rows) = n(columns)
# asymmetric ==> n(rows) != n(colums)

In [9]:
# predefined functions 
# .zeros ---> create an array in which all the elemets are 0


In [10]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [15]:
b=np.zeros([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# ones()  ==> create an array in which each element is 1.

In [17]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [18]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
type(a)

numpy.ndarray

In [20]:
print(a.shape,a.size)

(2, 3) 6


In [21]:
# .eye() ==> diagonal positional elements are 1and rest are 0

In [22]:
a=np.eye(4)

In [23]:
a # symmetric

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
a=np.eye(2,3)

In [28]:
a # asymmetric

array([[1., 0., 0.],
       [0., 1., 0.]])