In [1]:
import numpy as np

In [7]:
# diagonal function 
a=np.diag([1,2,3,4])

In [8]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
# randint ==> random number
# syntax ==> randint(min,max,totalnumbers)
a=np.random.randint(1,10,3)
a

array([2, 9, 9])

# rand() ==> function used to geenerate random number betweeen 0 and 1

# syntax == rand(number of values)

In [13]:
a=np.random.rand(5)
a

array([0.28024434, 0.94674136, 0.58260905, 0.77776029, 0.25841245])

In [14]:
# randn() ==> used to geenrate a random number from -3 to close 3 . may return positive or negative number
# syntax == random.randn(number of values)

In [16]:
a=np.random.randn(5)
a

array([-1.12894351,  0.35461711,  0.74468129, -0.81288306,  1.73045159])

In [17]:
# Reshaping data 

In [18]:
a=np.random.randint(1,50,12)
a

array([ 8,  8, 13, 40, 13,  4, 35, 20, 32, 36, 28, 17])

In [19]:
# n(rows) * n(col)= total elements than we can reshape only

In [20]:
a.shape

(12,)

In [21]:
a=a.reshape(2,6)

In [22]:
a

array([[ 8,  8, 13, 40, 13,  4],
       [35, 20, 32, 36, 28, 17]])

In [23]:
a=a.reshape(6,2)
a

array([[ 8,  8],
       [13, 40],
       [13,  4],
       [35, 20],
       [32, 36],
       [28, 17]])

In [24]:
a=a.reshape(4,3)
a

array([[ 8,  8, 13],
       [40, 13,  4],
       [35, 20, 32],
       [36, 28, 17]])

In [25]:
a=a.reshape(3,4)
a

array([[ 8,  8, 13, 40],
       [13,  4, 35, 20],
       [32, 36, 28, 17]])

In [26]:
a=a.reshape(12,1)
a

array([[ 8],
       [ 8],
       [13],
       [40],
       [13],
       [ 4],
       [35],
       [20],
       [32],
       [36],
       [28],
       [17]])

In [27]:
a=a.reshape(1,5)
a

ValueError: cannot reshape array of size 12 into shape (1,5)

In [28]:
# principal -1

a=a.reshape(-1,2)
a

array([[ 8,  8],
       [13, 40],
       [13,  4],
       [35, 20],
       [32, 36],
       [28, 17]])

In [29]:
# Seed function() ==> randint generates random numbers. Every time we run the program , new set of random numbers is generated . to solve this problem seed function is used.

In [30]:
np.random.seed(5)
a=np.random.randint(1,100,10)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [32]:
#view
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [33]:
#copy
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [34]:
b

array([0, 0, 0])

In [35]:
# conditional selection

In [36]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [38]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [39]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [41]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [43]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [44]:
# operations on array 

In [45]:
a=[1,2,3,4]
a=a*2
print(a)

[1, 2, 3, 4, 1, 2, 3, 4]


In [46]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [47]:
a*2

array([2, 4, 6, 8])

In [48]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [52]:
# operations
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [51]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [53]:
a+b

array([[ 6,  8],
       [10, 12]])

In [54]:
a-b

array([[-4, -4],
       [-4, -4]])

In [55]:
a*b

array([[ 5, 12],
       [21, 32]])

In [56]:
a//b

array([[0, 0],
       [0, 0]], dtype=int32)

In [57]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [59]:
b//a

array([[5, 3],
       [2, 2]], dtype=int32)

In [60]:
a=np.array([10,20,30,40,50])
np.min(a)

10

In [61]:
np.max(a)

50

In [62]:
np.argmin(a) # return index of min value

0

In [63]:
np.argmax(a)  # return index of max value

4

In [64]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [65]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [66]:
# Linspace function ==> returns value between a given range and with a same gap between consecutive elements 

In [67]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [68]:
# np.unique(arr,return_index=True,return_counts=True)


In [69]:
a=np.array([10,20,30,40,10,20,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [70]:
# horizontal and vertical stacking 

In [73]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [74]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])