### 1 Why numpy is better than list
### 2 How do you check shape size and dimension of an array
### 3 What is differrence between zeros, ones , eye, diagonal , unique,linspace function, hstack and vstack function, randomint,rand ,seed function
### 3 How do you create user defined array
### 4 Difference bw series and dataframe in pandas -- definition with example
### 5 How do you handle missing data in pandas
### 6 Diff bw describe method & info method in pandas
### 7 diff lock method and ilock method in pandas
### 8 why we use value_counts() in pandas
### 9 diff bw merge and concat in pandas 
### 10 how do you add row wise and column wise data in pandas
### 11 how do you rename column name using pandas
### 12 let suppose we have emp info dataset in which we have columns empid,ename,dept,working_hours,salary.Now you have to update to emp salary and 2 emp working_hours and then you have to create new columns using pandas let suppose we have a column dept in which sales , it and operations , now u have to create particular columns of all three depts 
### 13 Diff between univariate , bivariate and multivariate analysis with example
### 14 Diff bt discrete data and continous data 
### 15 What types of chart u use when you have categorical data and numerical data
​

In [1]:
import numpy as np

## 1. Why is NumPy better than lists?
NumPy is better than lists for several reasons:

Performance: NumPy arrays are more efficient for numerical computations as they are implemented in C and optimized for performance.

Memory: NumPy arrays are more memory-efficient as they store elements of the same type, unlike lists that can store elements of different types.

Convenience: NumPy provides a wide range of mathematical functions and operations that can be applied to arrays, making it easier to perform complex calculations.

Vectorization: NumPy supports vectorized operations, which are faster than using loops for element-wise operations on lists.

## 2. How do you check the shape, size, and dimension of an array?
Shape: array.shape returns a tuple representing the dimensions of the array.
    
Size: array.size returns the total number of elements in the array.
    
Dimension: array.ndim returns the number of dimensions of the array.

In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
a.shape

(2, 4)

In [11]:
a.size

8

In [13]:
a.ndim

2

## 3. What is the difference between zeros, ones, eye, diagonal, unique, linspace functions, hstack and vstack functions, randint, rand, seed functions?
zeros: Creates an array filled with zeros. np.zeros((3, 3))
    
ones: Creates an array filled with ones. np.ones((3, 3))

eye: Creates an identity matrix. np.eye(3)

diagonal: Extracts or constructs a diagonal array. np.diag([1, 2, 3])

unique: Finds unique elements in an array. np.unique(array)


linspace: Generates linearly spaced values between two points. np.linspace(0, 10, 5)

hstack: Stacks arrays horizontally (column-wise). np.hstack((array1, array2))

vstack: Stacks arrays vertically (row-wise). np.vstack((array1, array2))

randint: Generates random integers. np.random.randint(0, 10, 5)

rand: Generates random floats in the range [0, 1). np.random.rand(3, 3)

seed: Sets the random seed for reproducibility. np.random.seed(42)

In [16]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
b=np.unique(a)
b

array([0, 1, 2, 3])

In [23]:
c=np.linspace(0,10,5)
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
c=np.hstack(a)
c

array([1, 0, 0, 0, 2, 0, 0, 0, 3])

In [25]:
c=np.vstack(a)
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
c=np.random.randint(0, 10, 5)
c

array([0, 7, 5, 3, 3])

In [27]:
c= np.random.rand(3, 3)
c

array([[0.56665096, 0.44626598, 0.28627175],
       [0.61516914, 0.97625355, 0.63077415],
       [0.33483039, 0.7894667 , 0.80575108]])

In [32]:
np.random.seed(42)
a=np.random.randint(1,100,10)
a

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

## 6. How do you handle missing data in Pandas?
Drop missing values: df.dropna()

Fill missing values: df.fillna(value)

Forward fill: df.fillna(method='ffill')

Backward fill: df.fillna(method='bfill')


In [33]:
import pandas as pd

In [73]:

# Sample DataFrame with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, np.nan, 35, 40],
    'Salary': [50000, 60000, np.nan, 80000],
    'Department': ['HR', 'IT', 'Finance', np.nan]
}

data_df = pd.DataFrame(data)
print("Original DataFrame:")
data_df


Original DataFrame:


Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  35.0      NaN    Finance
3    David  40.0  80000.0        NaN

In [37]:
dfx=data_df.dropna()
dfx

Name   Age   Salary Department
0  Alice  25.0  50000.0         HR

In [38]:
dfx=data_df.fillna(0)
dfx

Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   0.0  60000.0         IT
2  Charlie  35.0      0.0    Finance
3    David  40.0  80000.0          0

In [39]:
dfx= data_df.fillna(method='ffill') # -- fills with the forward value
dfx

Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  25.0  60000.0         IT
2  Charlie  35.0  60000.0    Finance
3    David  40.0  80000.0    Finance

In [40]:
dfx= data_df.fillna(method='bfill') # -- fills with the backward value
dfx

Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob  35.0  60000.0         IT
2  Charlie  35.0  80000.0    Finance
3    David  40.0  80000.0        NaN

## 5. Difference between Series and DataFrame in Pandas with an example
Series: A one-dimensional labeled array capable of holding any data type. 

DataFrame: A two-dimensional labeled data structure with columns of potentially different types. Example:


In [42]:
series = pd.Series([1, 2, 3, 4])
print(series)

0    1
1    2
2    3
3    4
dtype: int64


In [43]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
dataframe = pd.DataFrame(data)
dataframe

Name  Age
0  Alice   25
1    Bob   30

## 7. Difference between describe method and info method in Pandas
describe: Provides summary statistics of numerical columns. 

info: Provides a concise summary of the DataFrame including data types and non-null values.

In [85]:
df=pd.read_csv("C:\\Users\\DELL\\OneDrive\\Desktop\\Regex\\Adv Python\\Attrition.csv")
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [46]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

## 8. Difference between loc and iloc methods in Pandas

loc: Accesses data using labels (index or column names)

iloc: Accesses data using integer-location based indexing.


In [48]:
data_df

Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  35.0      NaN    Finance
3    David  40.0  80000.0        NaN

In [60]:
x=data_df.loc[1,'Name']
x

'Bob'

In [58]:
x=data_df.iloc[0,0]
x

'Alice'

## 9. Why do we use value_counts() in Pandas?
value_counts() is used to count the unique values in a Series. It is useful for understanding the distribution of categorical data.


In [62]:
df['Department'].value_counts()


Research & Development    961
Sales                     446
Human Resources            63
Name: Department, dtype: int64

## 10. Difference between merge and concat in Pandas
merge: Combines DataFrames based on keys or columns. Similar to SQL joins

concat: Concatenates DataFrames along a particular axis (rows or columns).

In [63]:
pd.merge(df1, df2, on='key')


NameError: name 'df1' is not defined

In [64]:
data_df

Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  35.0      NaN    Finance
3    David  40.0  80000.0        NaN

In [65]:
pd.merge(df, data_df, on='Department')

Empty DataFrame
Columns: [Age_x, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager, Name, Age_y, Salary]
Index: []

[0 rows x 38 columns]

In [67]:
pd.concat([df, data_df], axis=1)


Age Attrition     BusinessTravel  DailyRate              Department  \
0     41       Yes      Travel_Rarely       1102                   Sales   
1     49        No  Travel_Frequently        279  Research & Development   
2     37       Yes      Travel_Rarely       1373  Research & Development   
3     33        No  Travel_Frequently       1392  Research & Development   
4     27        No      Travel_Rarely        591  Research & Development   
...   ..       ...                ...        ...                     ...   
1465  36        No  Travel_Frequently        884  Research & Development   
1466  39        No      Travel_Rarely        613  Research & Development   
1467  27        No      Travel_Rarely        155  Research & Development   
1468  49        No  Travel_Frequently       1023                   Sales   
1469  34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  TrainingTimesLastYear WorkLifeBalance  \
0                  1  ...                      0               1   
1                  2  ...                      3               3   
2                  4  ...                      3               3   
3                  5  ...                      3               3   
4                  7  ...                      3               3   
...              ...  ...                    ...             ...   
1465            2061  ...                      3               3   
1466            2062  ...                      5               3   
1467            2064  ...                      0               3   
1468            2065  ...                      3               2   
1469            2068  ...                      3               4   

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                  6                   4                        0   
1                 10                   7                        1   
2                  0                   0                        0   
3                  8                   7                        3   
4                  2                   2                        2   
...              ...                 ...                      ...   
1465               5                   2                        0   
1466               7                   7                        1   
1467               6                   2                        0   
1468               9                   6                        0   
1469               4                   3                        1   

     YearsWithCurrManager     Name   Age   Salary  Department  
0                       5    Alice  25.0  50000.0          HR  
1                       7      Bob   NaN  60000.0          IT  
2                       0  Charlie  35.0      NaN     Finance  
3                       0    David  40.0  80000.0         NaN  
4                       2      NaN   NaN      NaN         NaN  
...                   ...      ...   ...      ...         ...  
1465                    3      NaN   NaN      NaN         NaN  
1466                    7      NaN   NaN      NaN         NaN  
1467                    3      NaN   NaN      NaN         NaN  
1

## 11. How do you add row-wise and column-wise data in Pandas?
Row-wise: df.append(new_row), pd.concat([df, new_row_df], axis=0)

Column-wise: df['new_column'] = values, pd.concat([df, new_column_df], axis=1)

In [88]:
# New row to add
new_row = {'Name': 'Alex', 'Age': 35}

# Adding the new row
data_df = data_df.append(new_row,ignore_index=True)

print("DataFrame after adding new row using append():")
data_df

DataFrame after adding new row using append():


Name   Age   Salary Department    City
0    Alice  25.0  50000.0         HR  Jaipur
1      Bob   NaN  60000.0         IT  Jaipur
2  Charlie  35.0      NaN    Finance  Jaipur
3    David  40.0  80000.0        NaN  Jaipur
4     Alex  35.0      NaN        NaN     NaN
5     Alex  35.0      NaN        NaN     NaN

In [92]:
# Sample DataFrame
data_df = pd.DataFrame(data)

# New column values
new_column_values = ['Jaipur', 'Jodhpur','Kota','Delhi']

# Adding the new column
data_df['City'] = new_column_values

data_df


Name   Age   Salary Department     City
0    Alice  25.0  50000.0         HR   Jaipur
1      Bob   NaN  60000.0         IT  Jodhpur
2  Charlie  35.0      NaN    Finance     Kota
3    David  40.0  80000.0        NaN    Delhi

In [83]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely     1102.0                   Sales   
1      49        No  Travel_Frequently      279.0  Research & Development   
2      37       Yes      Travel_Rarely     1373.0  Research & Development   
3      33        No  Travel_Frequently     1392.0  Research & Development   
4      27        No      Travel_Rarely      591.0  Research & Development   
...   ...       ...                ...        ...                     ...   
1468   49        No  Travel_Frequently     1023.0                   Sales   
1469   34        No      Travel_Rarely      628.0  Research & Development   
1470   35       NaN                NaN        NaN                     NaN   
1471   35       NaN                NaN        NaN                     NaN   
1472   35       NaN                NaN        NaN                     NaN   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                  1.0        2.0  Life Sciences            1.0   
1                  8.0        1.0  Life Sciences            1.0   
2                  2.0        2.0          Other            1.0   
3                  3.0        4.0  Life Sciences            1.0   
4                  2.0        1.0        Medical            1.0   
...                ...        ...            ...            ...   
1468               2.0        3.0        Medical            1.0   
1469               8.0        3.0        Medical            1.0   
1470               NaN        NaN            NaN            NaN   
1471               NaN        NaN            NaN            NaN   
1472               NaN        NaN            NaN            NaN   

      EmployeeNumber  ...  StandardHours StockOptionLevel  TotalWorkingYears  \
0                1.0  ...           80.0              0.0                8.0   
1                2.0  ...           80.0              1.0               10.0   
2                4.0  ...           80.0              0.0                7.0   
3                5.0  ...           80.0              0.0                8.0   
4                7.0  ...           80.0              1.0                6.0   
...              ...  ...            ...              ...                ...   
1468          2065.0  ...           80.0              0.0               17.0   
1469          2068.0  ...           80.0              0.0                6.0   
1470             NaN  ...            NaN              NaN                NaN   
1471             NaN  ...            NaN              NaN                NaN   
1472             NaN  ...            NaN              NaN                NaN   

      TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  \
0                       0.0              1.0            6.0   
1                       3.0              3.0           10.0   
2                       3.0              3.0            0.0   
3                       3.0              3.0            8.0   
4                       3.0              3.0            2.0   
...                     ...              ...            ...   
1468                    3.0              2.0            9.0   
1469                    3.0              4.0            4.0   
1470                    NaN              NaN            NaN   
1471                    NaN              NaN            NaN   
1472                    NaN              NaN            NaN   

      YearsInCurrentRole YearsSinceLastPromotion  YearsWithCurrManager  \
0                    4.0                     0.0                   5.0   
1                    7.0                     1.0                   7.0   
2                    0.0                     0.0                   0.0   
3                    7.0                     3.0                   0.0   
4                    2.0                     2.0                   2.0   
...                  ...                     ...                   ...   
1468                 6.0                

In [93]:
data_df

Name   Age   Salary Department     City
0    Alice  25.0  50000.0         HR   Jaipur
1      Bob   NaN  60000.0         IT  Jodhpur
2  Charlie  35.0      NaN    Finance     Kota
3    David  40.0  80000.0        NaN    Delhi

## 12. How do you rename a column name using Pandas?

df.rename(columns={'old_name': 'new_name'}, inplace=True)


In [94]:
data_df.rename(columns={'Department': 'Dept'}, inplace=True)
data_df

Name   Age   Salary     Dept     City
0    Alice  25.0  50000.0       HR   Jaipur
1      Bob   NaN  60000.0       IT  Jodhpur
2  Charlie  35.0      NaN  Finance     Kota
3    David  40.0  80000.0      NaN    Delhi

## 14. Difference between univariate, bivariate, and multivariate analysis with examples
Univariate: Analysis of a single variable. Example: Histogram of ages.

Bivariate: Analysis of two variables to find relationships. Example: Scatter plot of height vs. weight.

Multivariate: Analysis of more than two variables. Example: Multivariate regression.

## 15. Difference between discrete data and continuous data
Discrete Data: Countable and finite. Example: Number of students in a class.

Continuous Data: Measurable and infinite. Example: Height of students.

## 16. Types of charts for categorical and numerical data
Categorical Data: Bar chart, pie chart.

Numerical Data: Histogram, box plot, scatter plot.